language: java
jdk:
- oraclejdk9
services:
  - postgresql
before_script:
  - psql -c "create user blendocu with password 'blend';" -U postgres
  - psql -c "create database blendocu;" -U postgres
  - psql -c "grant all on database blendocu to blendocu;" -U postgres